config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope '(:locale)', locale: /en|uk|ru/ do
    root to: 'home#show'
    get 'index.html', to: 'home#show'
    get 'about.html', to: 'home#about'
    get 'contact.html', to: 'home#contact'
    # get 'photos.html', to: 'photos#index'
    # get 'items.html', to: 'items#index'

    resources :photos, only: %i[index] do
      resources :items, only: %i[index] do
      end
    end

    namespace :admin do
      root to: 'home#show'
      resources :photos do
        delete :destroy_image, on: :member
        resources :items do
          delete :destroy_image, on: :member
        end
      end
    end

    # devise_for :users,
    #           path_names: {sign_in: 'login',
    #                        sign_out: 'logout',
    #                        password: 'secret',
    #                        sign_up: 'registration'},
    #           controllers: {sessions: 'users/sessions',
    #                         registrations: 'users/registrations',
    #                         passwords: 'users/passwords',
    #                         confirmations: 'users/confirmations',
    #                         unlocks: 'users/unlocks',
    #           }
    devise_for :users, skip: %i[sessions registrations passwords confirmations unlock]
    as :user do
      get 'login.html', to: 'users/sessions#new', as: :new_user_session
      post 'login.html', to: 'users/sessions#create', as: :user_session
      match 'logout.html', to: 'users/sessions#destroy', as: :destroy_user_session, via: Devise.mappings[:user].sign_out_via

      get 'registration.html', to: 'users/registrations#new', as: :new_user_registration
      post 'registration.html', to: 'users/registrations#create', as: :user_registration
      get 'edit-registration.html', to: 'users/registrations#edit', as: :edit_user_registration
      patch 'registration.html', to: 'users/registrations#update', as: :patch_user_registration
      delete 'registration.html', to: 'users/registrations#destroy', as: :delete_user_registration
      delete 'remove-avatar/:id', to: 'users/registrations#destroy_avatar', as: :delete_user_avatar_registration

      get 'recover-password.html', to: 'users/passwords#new', as: :new_user_password
      post 'recover-password.html', to: 'users/passwords#create'
      get 'edit-recover-password.html', to: 'users/passwords#edit', as: :edit_user_password
      patch 'recover-password.html', to: 'users/passwords#update', as: :user_password
      put 'recover-password.html', to: 'users/passwords#update'

      get 'confirmation.html', to: 'users/confirmations#new', as: :new_user_confirmation
      get 'show-confirmation.html', to: 'users/confirmations#show', as: :user_confirmation
      post 'show-confirmation.html', to: 'users/confirmations#create'

      get 'unlock.html', to: 'users/unlocks#new', as: :new_user_unlock
      get 'show-unlock.html', to: 'users/unlocks#show', as: :user_unlock
      post 'show-unlock.html', to: 'users/unlocks#create'
    end

    #match '*a', to: 'admin/errors#not_found', via: :all unless Rails.env.development?
    #match '*a', to: 'admin/errors#not_found', via: :all
  end
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/photo.rb
# frozen_string_literal: true

class Photo < ApplicationRecord
  has_many :items, dependent: :destroy
  has_one_attached :image
  validates :image, presence: true
  default_scope -> { order(:created_at) }
end

app/controllers/admin/photos_controller.rb
# frozen_string_literal: true

class Admin::PhotosController < Admin::BaseController
  before_action :photo, only: %i[show edit update destroy destroy_image]

  def index
    @photos = Photo.all
  end

  def new
    @photo = Photo.new
  end

  def show
  end

  def edit
  end

  def create
    @photo = Photo.new(photo_params)
    if @photo.save
      redirect_to admin_photos_path
    else
      render :new
    end
  end

  def update
    if @photo.update(photo_params)
      redirect_to admin_photos_path
    else
      render :edit
    end
  end

  def destroy
    flash[:error] = @photo.errors.full_messages unless @photo.destroy
    redirect_to admin_photos_path
  end

  def destroy_image
    image = ActiveStorage::Attachment.find_by(record_id: params[:id])
    image.purge
    redirect_to edit_admin_photo_path(@photo)
  end

  private

  def photo
    @photo ||= Photo.find(params[:id])
  end

  def photo_params
    params.require(:photo).permit(:name, :description, :image)
  end
end

app/controllers/photos_controller.rb
# frozen_string_literal: true

class PhotosController < BaseController
  def index
    @photos = Photo.all
  end
end

app/views/admin/photos/_form.html.slim
= f.error_notification
= f.input :image,
        placeholder: t('activerecord.models.photo.attributes.name.placeholder'),
        required: true,
        label: t('photo'),
        wrapper: :horizontal_file

= f.input :name,
        placeholder: t('activerecord.models.photo.attributes.name.placeholder'),
        required: true,
        label: t('name'),
        wrapper: :horizontal_form

= f.input :description,
        placeholder: t('activerecord.models.photo.attributes.description.placeholder'),
        required: true,
        label: t('description'),
        wrapper: :horizontal_form

app/views/admin/photos/edit.html.slim
= content_for(:title, t('admin.photos.edit work collection'))
= simple_form_for [:admin, @photo] do |f|
  /! Main content
  .content
    .container-fluid
      /! /.container-fluid
      /! /.content
      .row
        .col-md-8
          .card.card-yellow
            .card-header
              = t('admin.photos.edit work collection')
            .card-body
              - if @photo.image.attached?
                div style=("border: 1px solid #28A745; padding: 2px")
                  = image_tag @photo.image.variant(resize: '200'), alt: @photo.name
                = t('remove photo')
                |  #{link_to t('do it'), destroy_image_admin_photo_path(@photo), method: :delete}
                p
              - else
                p style=("border: 1px solid #28A745; padding: 2px")
                  = image_tag 'backend/default-image.jpg', size: 200, alt: 'Photo Image'
              = render partial: 'form', locals: {f: f}
            .card-footer
              = link_to  admin_photos_path, class: 'btn btn-danger'
                = t(:cancel)
              = f.submit t(:save), class: 'btn btn-success pull-right'

app/views/admin/photos/index.html.slim
= content_for(:title, t('admin.photos.work collection'))
/! Main content
.content
  .container-fluid
    /! /.container-fluid
    /! /.content
    .row
      .col-md-6.col-md-offset-10
        = link_to new_admin_photo_path, class: 'btn btn-success pull-right'
          i.fas.fa-plus
          |
          = t('admin.photos.add new work collection')
    .row
      p

    .row
      .col-12
        .card.card-yellow
          .card-header
            h3.card-title
              = t('admin.photos.work collection')
          /! /.card-header
          .card-body.p-0
            table.table.table-condensed
              thead
                tr
                  th style=("width: 50px")
                    = t('photo')
                  th style=("width: 30px")
                    = t('name')
                  th
                    = t('description')
                  th style=("width: 15px")
                    = t('action')

              tbody
                - @photos.each do |photo|
                  tr
                    td
                      - if photo.image.attached?
                        = link_to admin_photo_items_path(photo)
                          - if photo.image.present?
                            = image_tag photo.image.variant(resize: '50'), alt: photo.name
                              = photo.name
                      - else
                        = link_to admin_photo_items_path(photo)
                          = image_tag 'backend/default-image.jpg', size: 50, alt: 'Photo Image'
                    td
                      = photo.name
                    td
                      = photo.description
                    td
                      .btn-row
                        = link_to raw('<i class="far fa-edit"></i>'), edit_admin_photo_path(photo),
                                class: 'btn btn-sm btn-warning',
                                style: 'margin-right: 10px',
                                title: t('edit')
                        = link_to raw('<i class="far fa-trash-alt"></i>'), admin_photo_path(photo),
                                class: 'btn btn-sm btn-warning',
                                method: :delete,
                                data: {confirm: t('confirm')},
                                title: t('remove')
          /! /.card-body

app/views/admin/photos/new.html.slim
= content_for(:title, t('admin.photos.new work collection'))
= simple_form_for [:admin, @photo] do |f|
  /! Main content
  .content
    .container-fluid
      /! /.container-fluid
      /! /.content
      .row
        .col-md-8
          .card.card-yellow
            .card-header
              = t('admin.photos.new work collection')
            .card-body
              = render partial: 'form', locals: {f: f}
            .card-footer
              = link_to  admin_photos_path, class: 'btn btn-danger'
                = t(:cancel)
              = f.submit t(:save), class: 'btn btn-success pull-right'