config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope '(:locale)', locale: /en|uk|ru/ do
    root to: 'home#show'
    get 'index.html', to: 'home#show'
    get 'about.html', to: 'home#about'
    get 'contact.html', to: 'home#contact'
    # get 'photos.html', to: 'photos#index'
    # get 'items.html', to: 'items#index'

    resources :photos, only: %i[index] do
      resources :items, only: %i[index] do
      end
    end

    namespace :admin do
      root to: 'home#show'
      resources :photos do
        delete :destroy_image, on: :member
        resources :items do
          delete :destroy_image, on: :member
        end
      end
    end

    # devise_for :users,
    #           path_names: {sign_in: 'login',
    #                        sign_out: 'logout',
    #                        password: 'secret',
    #                        sign_up: 'registration'},
    #           controllers: {sessions: 'users/sessions',
    #                         registrations: 'users/registrations',
    #                         passwords: 'users/passwords',
    #                         confirmations: 'users/confirmations',
    #                         unlocks: 'users/unlocks',
    #           }
    devise_for :users, skip: %i[sessions registrations passwords confirmations unlock]
    as :user do
      get 'login.html', to: 'users/sessions#new', as: :new_user_session
      post 'login.html', to: 'users/sessions#create', as: :user_session
      match 'logout.html', to: 'users/sessions#destroy', as: :destroy_user_session, via: Devise.mappings[:user].sign_out_via

      get 'registration.html', to: 'users/registrations#new', as: :new_user_registration
      post 'registration.html', to: 'users/registrations#create', as: :user_registration
      get 'edit-registration.html', to: 'users/registrations#edit', as: :edit_user_registration
      patch 'registration.html', to: 'users/registrations#update', as: :patch_user_registration
      delete 'registration.html', to: 'users/registrations#destroy', as: :delete_user_registration
      delete 'remove-avatar/:id', to: 'users/registrations#destroy_avatar', as: :delete_user_avatar_registration

      get 'recover-password.html', to: 'users/passwords#new', as: :new_user_password
      post 'recover-password.html', to: 'users/passwords#create'
      get 'edit-recover-password.html', to: 'users/passwords#edit', as: :edit_user_password
      patch 'recover-password.html', to: 'users/passwords#update', as: :user_password
      put 'recover-password.html', to: 'users/passwords#update'

      get 'confirmation.html', to: 'users/confirmations#new', as: :new_user_confirmation
      get 'show-confirmation.html', to: 'users/confirmations#show', as: :user_confirmation
      post 'show-confirmation.html', to: 'users/confirmations#create'

      get 'unlock.html', to: 'users/unlocks#new', as: :new_user_unlock
      get 'show-unlock.html', to: 'users/unlocks#show', as: :user_unlock
      post 'show-unlock.html', to: 'users/unlocks#create'
    end

    #match '*a', to: 'admin/errors#not_found', via: :all unless Rails.env.development?
    #match '*a', to: 'admin/errors#not_found', via: :all
  end
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_flash.html.slim
p.notice= notice
p.alert= alert

app/views/shared/_foot.html.erb
<!--<script src="js/jquery-3.3.1.min.js"></script>-->
<!--<script src="js/jquery-migrate-3.0.1.min.js"></script>-->
<!--<script src="js/jquery-ui.js"></script>-->
<!--<script src="js/popper.min.js"></script>-->
<!--<script src="js/bootstrap.min.js"></script>-->
<!--<script src="js/owl.carousel.min.js"></script>-->
<!--<script src="js/jquery.stellar.min.js"></script>-->
<!--<script src="js/jquery.countdown.min.js"></script>-->
<!--<script src="js/jquery.magnific-popup.min.js"></script>-->
<!--<script src="js/bootstrap-datepicker.min.js"></script>-->
<!--<script src="js/aos.js"></script>-->

<!--<script src="js/jquery.fancybox.min.js"></script>-->

<!--<script src="js/main.js"></script>-->

app/views/shared/_footer.html.slim
.row.justify-content-center
  .col-md-12.text-center.py-5
    p
      /! Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0.
      |  Copyright © 2020
      / javascript:
         document.write(new Date().getFullYear());
      |  All rights reserved | This template is made with
      i.icon-heart aria-hidden="true"
      |  by
      a href="https://colorlib.com" target="_blank"  Colorlib
/ ! Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0.

= javascript_include_tag 'frontend', media: 'all', 'data-turbolinks-track': 'reload'

app/views/shared/_head.html.slim
title Shutter — Colorlib Website Template
meta charset="utf-8" /
meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport" /
link href="https://fonts.googleapis.com/css?family=Quicksand:300,400,500,700,900" rel="stylesheet" /
/ link href="fonts/icomoon/style.css" rel="stylesheet" /
/ link href="css/bootstrap.min.css" rel="stylesheet" /
/ link href="css/magnific-popup.css" rel="stylesheet" /
/ link href="css/jquery-ui.css" rel="stylesheet" /
/ link href="css/owl.carousel.min.css" rel="stylesheet" /
/ link href="css/owl.theme.default.min.css" rel="stylesheet" /
/ link href="css/bootstrap-datepicker.css" rel="stylesheet" /
/ link href="fonts/flaticon/font/flaticon.css" rel="stylesheet" /
/ link href="css/aos.css" rel="stylesheet" /
/ link href="css/fancybox.min.css" rel="stylesheet" /
/ link href="css/style.css" rel="stylesheet" /

app/views/shared/_header.html.slim
.site-mobile-menu
  .site-mobile-menu-header
    .site-mobile-menu-close.mt-3
      span.icon-close2.js-menu-toggle
  .site-mobile-menu-body
header.header-bar.d-flex.d-lg-block.align-items-center data-aos="fade-left"
  .site-logo
    a href="/index.html"  Logo
  .d-inline-block.d-xl-none.ml-md-0.ml-auto.py-3 style=("position: relative; top: 3px;")
    a.site-menu-toggle.js-menu-toggle.text-white href="#"
      span.icon-menu.h3
  .main-menu
    ul.js-clone-nav
      li
        a href="/index.html" Home
      / li
      /   a href="/photos.html"  Photos
      li
        a href="/about.html"  About Me
      / li
      /   a href="blog.html"  Blog
      li
        a href="contact.html"  Contact
    ul.social.js-clone-nav
      li
        a href="#"
          span.icon-facebook
      li
        a href="#"
          span.icon-twitter
      li
        a href="#"
          span.icon-instagram
    ul.js-clone-nav
      li
        .frontend-login
          p
          - if current_user
            p
              = t('welcome')
              | &nbsp;
            p
              = link_to admin_root_path
                = current_user.email
            p
              = link_to destroy_user_session_path, method: :delete
                = t('devise.custom.log out')
          - else
            = t('welcome')
            | &nbsp;
            = t('devise.custom.guest')
            p
              = link_to new_user_session_path
                = t('devise.custom.log in')