config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope '(:locale)', locale: /en|uk|ru/ do
    root to: 'home#show'
    get 'index.html', to: 'home#show'
    get 'about.html', to: 'home#about'
    get 'contact.html', to: 'home#contact'
    # get 'photos.html', to: 'photos#index'
    # get 'items.html', to: 'items#index'

    resources :photos, only: %i[index] do
      resources :items, only: %i[index] do
      end
    end

    namespace :admin do
      root to: 'home#show'
      resources :photos do
        delete :destroy_image, on: :member
        resources :items do
          delete :destroy_image, on: :member
        end
      end
    end

    # devise_for :users,
    #           path_names: {sign_in: 'login',
    #                        sign_out: 'logout',
    #                        password: 'secret',
    #                        sign_up: 'registration'},
    #           controllers: {sessions: 'users/sessions',
    #                         registrations: 'users/registrations',
    #                         passwords: 'users/passwords',
    #                         confirmations: 'users/confirmations',
    #                         unlocks: 'users/unlocks',
    #           }
    devise_for :users, skip: %i[sessions registrations passwords confirmations unlock]
    as :user do
      get 'login.html', to: 'users/sessions#new', as: :new_user_session
      post 'login.html', to: 'users/sessions#create', as: :user_session
      match 'logout.html', to: 'users/sessions#destroy', as: :destroy_user_session, via: Devise.mappings[:user].sign_out_via

      get 'registration.html', to: 'users/registrations#new', as: :new_user_registration
      post 'registration.html', to: 'users/registrations#create', as: :user_registration
      get 'edit-registration.html', to: 'users/registrations#edit', as: :edit_user_registration
      patch 'registration.html', to: 'users/registrations#update', as: :patch_user_registration
      delete 'registration.html', to: 'users/registrations#destroy', as: :delete_user_registration
      delete 'remove-avatar/:id', to: 'users/registrations#destroy_avatar', as: :delete_user_avatar_registration

      get 'recover-password.html', to: 'users/passwords#new', as: :new_user_password
      post 'recover-password.html', to: 'users/passwords#create'
      get 'edit-recover-password.html', to: 'users/passwords#edit', as: :edit_user_password
      patch 'recover-password.html', to: 'users/passwords#update', as: :user_password
      put 'recover-password.html', to: 'users/passwords#update'

      get 'confirmation.html', to: 'users/confirmations#new', as: :new_user_confirmation
      get 'show-confirmation.html', to: 'users/confirmations#show', as: :user_confirmation
      post 'show-confirmation.html', to: 'users/confirmations#create'

      get 'unlock.html', to: 'users/unlocks#new', as: :new_user_unlock
      get 'show-unlock.html', to: 'users/unlocks#show', as: :user_unlock
      post 'show-unlock.html', to: 'users/unlocks#create'
    end

    #match '*a', to: 'admin/errors#not_found', via: :all unless Rails.env.development?
    #match '*a', to: 'admin/errors#not_found', via: :all
  end
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/admin/home_controller.rb
# frozen_string_literal: true

class Admin::HomeController < Admin::BaseController
  def show
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < BaseController
  def show
    @photos = Photo.all
  end

  def about
  end
end

app/views/home/about.html.slim
.row.justify-content-center
  .col-md-6.pt-4
    figure.mb-5 data-aos="fade-up"
      = image_tag 'backend/default-avatar.png', alt: 'Image', class: 'img-fluid'
    h2.text-white.mb-4 data-aos="fade-up"  Hey There! I'm Rhea
    .row data-aos="fade-up"
      .col-md-12
        p
          | Lorem ipsum dolor sit amet, consectetur
          a href="#"  adipisicing
          |  elit. Ipsa explicabo quasi cum, laudantium neque at veniam itaque atque
          a href="#"  necessitatibus
          |  temporibus! Beatae sit soluta magni neque autem, suscipit dolorem, quo alias.
        p
          |  Similique deserunt sit accusamus ipsum optio. Quia, sapiente saepe culpa ad nemo velit,
          a href="#"  veritatis
          |  numquam impedit voluptate quo tempore. Perferendis suscipit dolores, ducimus esse cupiditate possimus quae quis iusto rem?
        p Excepturi soluta maxime velit vitae tempore corporis, aliquid quidem modi libero! Optio minima esse hic repellendus a dolor perferendis dolore impedit quis et! Minus maxime itaque beatae totam eos reiciendis.
        p.mb-5 Ad veritatis eos dicta, animi et voluptates iusto, excepturi corporis amet, laboriosam, officiis libero. Odio excepturi aliquid suscipit nobis odit. Tenetur expedita impedit error consequatur sunt voluptatum voluptate voluptatem vitae!
        p cass="mt-4"
          | Thanks!
          br/
          | Rhea M.

app/views/home/contact.html.slim
.row.justify-content-center
  .col-md-6.pt-4 data-aos="fade-up"
    h2.text-white.mb-4 Contact Me
    .row
      .col-md-12
        p.mb-5
          | Lorem ipsum dolor sit amet, consectetur
          a href="#"  adipisicing
          |  elit. Ipsa explicabo quasi cum, laudantium neque at veniam itaque atque
          a href="#"  necessitatibus
          |  temporibus! Beatae sit soluta magni neque autem, suscipit dolorem, quo alias.
        .row
          .col-md-12
            form action="#"
              .row.form-group
                .col-md-6.mb-3.mb-md-0
                  label.text-white for="fname"  First Name
                  input#fname.form-control type="text" /
                .col-md-6
                  label.text-white for="lname"  Last Name
                  input#lname.form-control type="text" /
              .row.form-group
                .col-md-12
                  label.text-white for="email"  Email
                  input#email.form-control type="email" /
              .row.form-group
                .col-md-12
                  label.text-white for="subject"  Subject4
                  input#subject.form-control type="subject" /
              .row.form-group.mb-5
                .col-md-12
                  label.text-white for="message"  Message
                  textarea#message.form-control cols="30" name="message" placeholder=("Write your notes or questions here...") rows="7"
              .row.form-group
                .col-md-12
                  input.btn.btn-primary.btn-md.text-white type="submit" value=("Send Message") /

app/views/home/show.html.slim
.row.align-items-stretch
  - @photos.each do |photo|
    - if photo.image.attached?
      .col-6.col-md-6.col-lg-4 data-aos="fade-up" data-aos-delay="100"
        = link_to photo_items_path(photo), class: 'd-block photo-item'
          = image_tag photo.image, alt: 'Image', class: 'img-fluid'
          .photo-text-more
            .photo-text-more
              h3.heading
                = photo.name
              span.meta
                | #{photo.items.count} фото
  = render partial: 'items/add'